//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.02 at 12:17:02 PM CEST 
//


package eu.fbk.textpro.wrapper;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }
    /**
     * Create an instance of {@link Textpro.Server }
     * 
     */
    public Textpro.Server createTextproServer() {
        return new Textpro.Server();
    }
    /**
     * Create an instance of {@link Textpro }
     * 
     */
    public Textpro createTextpro() {
        return new Textpro();
    }

    /**
     * Create an instance of {@link Textpro.Modules }
     * 
     */
    public Textpro.Modules createTextproModules() {
        return new Textpro.Modules();
    }

    /**
     * Create an instance of {@link Textpro.Modules.Module }
     * 
     */
    public Textpro.Modules.Module createTextproModulesModule() {
        return new Textpro.Modules.Module();
    }

    /**
     * Create an instance of {@link Textpro.Modules.Module.Params }
     * 
     */
    public Textpro.Modules.Module.Params createTextproModulesModuleParams() {
        return new Textpro.Modules.Module.Params();
    }

    /**
     * Create an instance of {@link Textpro.Modules.Module.Output }
     * 
     */
    public Textpro.Modules.Module.Output createTextproModulesModuleOutput() {
        return new Textpro.Modules.Module.Output();
    }

    /**
     * Create an instance of {@link Textpro.Modules.Module.Input }
     * 
     */
    public Textpro.Modules.Module.Input createTextproModulesModuleInput() {
        return new Textpro.Modules.Module.Input();
    }

    /**
     * Create an instance of {@link Textpro.Resources }
     * 
     */
    public Textpro.Resources createTextproResources() {
        return new Textpro.Resources();
    }

    /**
     * Create an instance of {@link Textpro.Property }
     * 
     */
    public Textpro.Property createTextproProperty() {
        return new Textpro.Property();
    }

    /**
     * Create an instance of {@link Textpro.Modules.Module.Cmd }
     * 
     */
    public Textpro.Modules.Module.Cmd createTextproModulesModuleCmd() {
        return new Textpro.Modules.Module.Cmd();
    }

    /**
     * Create an instance of {@link Textpro.Modules.Module.Params.Param }
     * 
     */
    public Textpro.Modules.Module.Params.Param createTextproModulesModuleParamsParam() {
        return new Textpro.Modules.Module.Params.Param();
    }

    /**
     * Create an instance of {@link Textpro.Modules.Module.Output.Field }
     * 
     */
    public Textpro.Modules.Module.Output.Field createTextproModulesModuleOutputField() {
        return new Textpro.Modules.Module.Output.Field();
    }

    /**
     * Create an instance of {@link Textpro.Modules.Module.Output.Header }
     *
     */
    public Textpro.Modules.Module.Output.Header createTextproModulesModuleOutputHeader() {
        return new Textpro.Modules.Module.Output.Header();
    }

    /**
     * Create an instance of {@link Textpro.Modules.Module.Input.Field }
     * 
     */
    public Textpro.Modules.Module.Input.Field createTextproModulesModuleInputField() {
        return new Textpro.Modules.Module.Input.Field();
    }

    /**
     * Create an instance of {@link Textpro.Resources.Language }
     * 
     */
    public Textpro.Resources.Language createTextproResourcesLanguage() {
        return new Textpro.Resources.Language();
    }

}
