//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.27 at 09:37:55 AM CET 
//


package eu.fbk.textpro.modules.lemmapro;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Tagsets }
     * 
     */
    public Tagsets createTagsets() {
        return new Tagsets();
    }

    /**
     * Create an instance of {@link Tagsets.Tagset }
     * 
     */
    public Tagsets.Tagset createTagsetsTagset() {
        return new Tagsets.Tagset();
    }

    /**
     * Create an instance of {@link Tagsets.Tagset.Tag }
     * 
     */
    public Tagsets.Tagset.Tag createTagsetsTagsetTag() {
        return new Tagsets.Tagset.Tag();
    }

    /**
     * Create an instance of {@link Tagsets.Tagset.Tag.Rules }
     * 
     */
    public Tagsets.Tagset.Tag.Rules createTagsetsTagsetTagRules() {
        return new Tagsets.Tagset.Tag.Rules();
    }

    /**
     * Create an instance of {@link Tagsets.Tagset.Tag.Rules.Rule }
     * 
     */
    public Tagsets.Tagset.Tag.Rules.Rule createTagsetsTagsetTagRulesRule() {
        return new Tagsets.Tagset.Tag.Rules.Rule();
    }

}
