//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.30 at 03:16:15 PM CEST 
//


package eu.fbk.textpro.wrapper.utility.naf;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NAF }
     * 
     */
    public NAF createNAF() {
        return new NAF();
    }

    /**
     * Create an instance of {@link NAF.Timex3 }
     * 
     */
    public NAF.Timex3 createNAFTimex3() {
        return new NAF.Timex3();
    }

    /**
     * Create an instance of {@link NAF.Timex3 .Span }
     * 
     */
    public NAF.Timex3 .Span createNAFTimex3Span() {
        return new NAF.Timex3 .Span();
    }

    /**
     * Create an instance of {@link NAF.Chunks }
     * 
     */
    public NAF.Chunks createNAFChunks() {
        return new NAF.Chunks();
    }

    /**
     * Create an instance of {@link NAF.Chunks.Chunk }
     * 
     */
    public NAF.Chunks.Chunk createNAFChunksChunk() {
        return new NAF.Chunks.Chunk();
    }

    /**
     * Create an instance of {@link NAF.Chunks.Chunk.Span }
     * 
     */
    public NAF.Chunks.Chunk.Span createNAFChunksChunkSpan() {
        return new NAF.Chunks.Chunk.Span();
    }

    /**
     * Create an instance of {@link NAF.Terms }
     * 
     */
    public NAF.Terms createNAFTerms() {
        return new NAF.Terms();
    }

    /**
     * Create an instance of {@link NAF.Terms.Term }
     * 
     */
    public NAF.Terms.Term createNAFTermsTerm() {
        return new NAF.Terms.Term();
    }

    /**
     * Create an instance of {@link NAF.Terms.Term.Span }
     * 
     */
    public NAF.Terms.Term.Span createNAFTermsTermSpan() {
        return new NAF.Terms.Term.Span();
    }

    /**
     * Create an instance of {@link NAF.Text }
     * 
     */
    public NAF.Text createNAFText() {
        return new NAF.Text();
    }

    /**
     * Create an instance of {@link NAF.Timex3 .Span.Target }
     * 
     */
    public NAF.Timex3 .Span.Target createNAFTimex3SpanTarget() {
        return new NAF.Timex3 .Span.Target();
    }

    /**
     * Create an instance of {@link NAF.Chunks.Chunk.Span.Target }
     * 
     */
    public NAF.Chunks.Chunk.Span.Target createNAFChunksChunkSpanTarget() {
        return new NAF.Chunks.Chunk.Span.Target();
    }

    /**
     * Create an instance of {@link NAF.Terms.Term.Span.Target }
     * 
     */
    public NAF.Terms.Term.Span.Target createNAFTermsTermSpanTarget() {
        return new NAF.Terms.Term.Span.Target();
    }

    /**
     * Create an instance of {@link NAF.Text.Wf }
     * 
     */
    public NAF.Text.Wf createNAFTextWf() {
        return new NAF.Text.Wf();
    }

}
